# Data Preprocessing

In [ ]:
import os
import pandas as pd

In [ ]:
CATEGORIES_DATASET = os.path.join('../Data', 'amazon_categories.csv')
PRODUCTS_DATASET = os.path.join('../Data', 'amazon_products.csv')

categories_df = pd.read_csv(CATEGORIES_DATASET)
products_df = pd.read_csv(PRODUCTS_DATASET)

products_df.tail()

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth
1426332,B00R3LIKCO,American Flag Patriotic USA Classic 5 Panel Me...,https://m.media-amazon.com/images/I/71PDJFz6AA...,https://www.amazon.com/dp/B00R3LIKCO,4.2,0,14.95,0.00,112,False,0
1426333,B098BQ7ZQ3,Men's Baseball Cap - H2O-DRI Line Up Curved Br...,https://m.media-amazon.com/images/I/812Tycexs4...,https://www.amazon.com/dp/B098BQ7ZQ3,4.4,0,33.99,0.00,112,False,0
1426334,B07X1MVNT1,[4 Pack] Adjustable Eyeglasses and Sunglasses ...,https://m.media-amazon.com/images/I/61vvYW1S9J...,https://www.amazon.com/dp/B07X1MVNT1,3.6,0,8.54,0.00,112,False,0
1426335,B08XLBG8V9,Ax2002 Aviator Sunglasses,https://m.media-amazon.com/images/I/51+yjD4F1x...,https://www.amazon.com/dp/B08XLBG8V9,4.5,0,54.36,57.39,112,False,0
1426336,B07GH67QC8,in Hoc Signo Vinces Knights Templar Masonic Em...,https://m.media-amazon.com/images/I/91Kt2KQf0E...,https://www.amazon.com/dp/B07GH67QC8,4.9,0,18.79,0.00,112,False,0

In [ ]:
categories_df.head()
categories_df["category_id"] = categories_df["id"]
categories_df.drop(columns=["id"], inplace=True)
categories_df.head()

                      category_name  category_id
0          Beading & Jewelry Making            1
1                 Fabric Decorating            2
2       Knitting & Crochet Supplies            3
3              Printmaking Supplies            4
4  Scrapbooking & Stamping Supplies            5

In [ ]:
merged_df = products_df.merge(categories_df, on="category_id", how="left")
merged_df.head()

,asin,title,imgUrl,productURL,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth,category_name
0,B014TMV5YE,"Sion Softside Expandable Roller Luggage, Black...",https://m.media-amazon.com/images/I/815dLQKYIY...,https://www.amazon.com/dp/B014TMV5YE,4.5,0,139.99,0.00,104,False,2000,Suitcases
1,B07GDLCQXV,Luggage Sets Expandable PC+ABS Durable Suitcas...,https://m.media-amazon.com/images/I/81bQlm7vf6...,https://www.amazon.com/dp/B07GDLCQXV,4.5,0,169.99,209.99,104,False,1000,Suitcases
2,B07XSCCZYG,Platinum Elite Softside Expandable Checked Lug...,https://m.media-amazon.com/images/I/71EA35zvJB...,https://www.amazon.com/dp/B07XSCCZYG,4.6,0,365.49,429.99,104,False,300,Suitcases
3,B08MVFKGJM,Freeform Hardside Expandable with Double Spinn...,https://m.media-amazon.com/images/I/91k6NYLQyI...,https://www.amazon.com/dp/B08MVFKGJM,4.6,0,291.59,354.37,104,False,400,Suitcases
4,B01DJLKZBA,Winfield 2 Hardside Expandable Luggage with Sp...,https://m.media-amazon.com/images/I/61NJoaZcP9...,https://www.amazon.com/dp/B01DJLKZBA,4.5,0,174.99,309.99,104,False,400,Suitcases

In [ ]:
merged_df["product_id"] = merged_df["asin"].astype(str)
merged_df.drop(columns=["asin","imgUrl","productURL"], inplace=True)

,title,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth,category_name,product_id
0,"Sion Softside Expandable Roller Luggage, Black...",4.5,0,139.99,0.00,104,False,2000,Suitcases,B014TMV5YE
1,Luggage Sets Expandable PC+ABS Durable Suitcas...,4.5,0,169.99,209.99,104,False,1000,Suitcases,B07GDLCQXV
2,Platinum Elite Softside Expandable Checked Lug...,4.6,0,365.49,429.99,104,False,300,Suitcases,B07XSCCZYG
3,Freeform Hardside Expandable with Double Spinn...,4.6,0,291.59,354.37,104,False,400,Suitcases,B08MVFKGJM
4,Winfield 2 Hardside Expandable Luggage with Sp...,4.5,0,174.99,309.99,104,False,400,Suitcases,B01DJLKZBA

In [ ]:
PREPROCESSED_DATASET = os.path.join('../Data', 'preprocessed_data.csv')

merged_df.to_csv(PREPROCESSED_DATASET, index=False)
merged_df.head()

,title,stars,reviews,price,listPrice,category_id,isBestSeller,boughtInLastMonth,category_name,product_id
0,"Sion Softside Expandable Roller Luggage, Black...",4.5,0,139.99,0.00,104,False,2000,Suitcases,B014TMV5YE
1,Luggage Sets Expandable PC+ABS Durable Suitcas...,4.5,0,169.99,209.99,104,False,1000,Suitcases,B07GDLCQXV
2,Platinum Elite Softside Expandable Checked Lug...,4.6,0,365.49,429.99,104,False,300,Suitcases,B07XSCCZYG
3,Freeform Hardside Expandable with Double Spinn...,4.6,0,291.59,354.37,104,False,400,Suitcases,B08MVFKGJM
4,Winfield 2 Hardside Expandable Luggage with Sp...,4.5,0,174.99,309.99,104,False,400,Suitcases,B01DJLKZBA